### PR TITLE
My improvements.

### PR DESCRIPTION
**Pull request by KOLANICH**
1. Formatting was inconsistent. Transformed everything into tabs. Added .editorconfig. You should really install a plugin implementing its spec for your IDE.
2. fixed some formatting issues in python files.
3. implemented plugin autodiscovery in a dir and wide paths support (because on Windows an app can be jnstalled in a dir with non-ascii chars in path)

### CODE REVIEW

**Comment by tuncb** [comment]
Hi,
Thank you for your additions.
At this point of the library I don't want to add new features that can be implemented outside of the library by the caller app.
For this reason, I don't think I can accept the part of your additions related to auto discovary of plugins. 

However I find the addition of wide character functions really usefull. If you can isolate those parts I can add them to the library.
Otherwise I will create an issue and add the changes myself.

One comment related: I don't think the library should do something about error reporting after failing load library: 
inside DllLoader:load function
`std::cerr << dlerror() << std::endl;`
I guess dlerror can be called outside of this function as well by the caller.

**Comment by KOLANICH** [comment]
>However I find the addition of wide character functions really usefull. If you can isolate those parts I can add them to the library.

I can split them into a separate PR. But it'd be more convenient if you landed (rebased upon `master`) the formatting-fixing commits first (otherwise the IDE I use would automatically indent the edited parts of the source the way it us configured to indent code (I have found no way to disable this behavior) and the commit will be contaminated).

>One comment related: I don't think the library should do something about error reporting after failing load library:
inside DllLoader:load function
std::cerr << dlerror() << std::endl;
I guess dlerror can be called outside of this function as well by the caller.

It can, but mustn't. Implementation-specific (including platform-specific) stuff must not be called in any way other than through abstraction layers.

I guess that we should remove all the code dealing with importing symbols from shared libraries and rely on cross-platform wrappers around them: https://github.com/tocola/DyLib https://github.com/karel-burda/function-loader https://github.com/maddouri/dynalo https://github.com/MrZeusTheCoder/RLL .

>At this point of the library I don't want to add new features that can be implemented outside of the library by the caller app.
For this reason, I don't think I can accept the part of your additions related to auto discovary of plugins.

IMHO it defeats the purpose of using a library. When I use a library, I expect it to solve my problems for me. If I have to write the code like scanning plugins, then ... why do I need a library?

BTW, the autodiscovery code in this PR is ancient, here is some probably better one: https://github.com/HydrArgs/HydrArgs/blob/master/discoverer/discoverer.cpp . The things I don't like in it is that it executes ctors when loading libraries. I'd like it to:
1. it should be possible to require the plugin to be signed
2. first it should load the struct describing the plugin from the lib without executing any code from the lib
3. the ctors should be called if and only if the plugin was selected

I consider it as essential functionality and expect plugin frameworks to have it, so I wouldn't have to have it in my app code.

**Comment by tuncb** [comment]
Hi, 

For the error message, I don't think the library should show any error messages as this might not be what the caller wants. Probably a better way is to throw an exception here.

The reason I don't want any new features that can be implemented outside of the library is that I don't have time to maintain the library and I try to keep it managable. 
If you really like to continue the development you can continue in a fork, or if you really like I can transfer the repo to you as well.

What do you think?

**Comment by KOLANICH** [comment]
>Probably a better way is to throw an exception here.

Yeah, I have replaced with an exception.

>If you really like to continue the development you can continue in a fork, or if you really like I can transfer the repo to you as well.

>What do you think?

No, thank you. I just upstream my code in hope someone find it helpful. I am thinking about either writing an own one or about stopping reinventing wheel and just using (XP)COM.

**Pull request closed without merging**
